# -*- coding: utf-8 -*-
"""yfinance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jwZq-8y7BLGSEf5XnRaHhe9P25Up42s
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install yfinance -q

!pip install yfinance pandas numpy tqdm pyarrow -q

import subprocess, sys
subprocess.check_call([sys.executable, "-m", "pip", "install",
    "yfinance", "pandas", "numpy", "tqdm", "pyarrow",
    "lxml", "html5lib", "requests", "-q"])

import yfinance as yf
import pandas as pd
import numpy as np
import os, time, json, warnings, requests
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
warnings.filterwarnings("ignore")
print("✅ Libraries ready")

BASE        = "/content/drive/MyDrive/market_data"
RAW         = f"{BASE}/raw"
META        = f"{BASE}/raw_metadata"
PROCESSED   = f"{BASE}/processed"
QUALITY     = f"{BASE}/quality"

for p in [RAW, META, PROCESSED, QUALITY]:
    os.makedirs(p, exist_ok=True)
print("✅ Folders ready at:", BASE)

# ============================================================
# CELL 4 — Build ticker universe (Wikipedia 403 fix)
# ============================================================
import requests, io

# Spoof a real browser so Wikipedia doesn't block us
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    )
}

def fetch_wiki_tickers(url, possible_cols=("Symbol","Ticker","Ticker symbol")) -> list:
    try:
        html  = requests.get(url, headers=HEADERS, timeout=15).text
        dfs   = pd.read_html(io.StringIO(html))
        df    = dfs[0]
        for col in possible_cols:
            if col in df.columns:
                tickers = df[col].dropna().tolist()
                tickers = [str(t).replace(".","-").strip() for t in tickers]
                return [t for t in tickers if 1 <= len(t) <= 7]
        # auto-detect: find column whose values look like tickers
        for col in df.columns:
            sample = df[col].dropna().head(5).tolist()
            if all(str(v).isupper() and 1 <= len(str(v)) <= 6 for v in sample):
                tickers = df[col].dropna().tolist()
                return [str(t).replace(".","-").strip() for t in tickers]
        print(f"  ⚠️  No ticker col found. Columns: {list(df.columns)}")
        return []
    except Exception as e:
        print(f"  ⚠️  Failed: {url} — {e}")
        return []

print("Fetching ticker lists from Wikipedia…")
sp500    = fetch_wiki_tickers("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")
print(f"  S&P 500   : {len(sp500)}")

sp400    = fetch_wiki_tickers("https://en.wikipedia.org/wiki/List_of_S%26P_400_companies")
print(f"  S&P 400   : {len(sp400)}")

sp600    = fetch_wiki_tickers("https://en.wikipedia.org/wiki/List_of_S%26P_600_companies")
print(f"  S&P 600   : {len(sp600)}")

nasdaq100 = fetch_wiki_tickers(
    "https://en.wikipedia.org/wiki/Nasdaq-100",
    possible_cols=("Ticker","Symbol","Ticker symbol")
)
print(f"  NASDAQ-100: {len(nasdaq100)}")

djia30   = fetch_wiki_tickers(
    "https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average",
    possible_cols=("Symbol","Ticker")
)
print(f"  DJIA 30   : {len(djia30)}")

# GitHub CSVs as backup for Russell 1000 + extra coverage
GITHUB_CSVS = [
    # S&P 500 maintained CSV
    "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv",
    # Additional Russell 1000 proxy
    "https://raw.githubusercontent.com/rreichel3/US-Stock-Symbols/main/nyse/nyse_tickers.txt",
    "https://raw.githubusercontent.com/rreichel3/US-Stock-Symbols/main/nasdaq/nasdaq_tickers.txt",
    "https://raw.githubusercontent.com/rreichel3/US-Stock-Symbols/main/amex/amex_tickers.txt",
]

extra = []
for csv_url in GITHUB_CSVS:
    try:
        r = requests.get(csv_url, timeout=15)
        r.raise_for_status()
        if csv_url.endswith(".txt"):
            # plain text: one ticker per line
            tickers = [line.strip() for line in r.text.splitlines() if line.strip()]
        else:
            df = pd.read_csv(io.StringIO(r.text))
            col = next((c for c in ["Symbol","Ticker","symbol","ticker"] if c in df.columns), None)
            tickers = df[col].dropna().tolist() if col else []
        tickers = [str(t).replace(".","-").strip() for t in tickers if 1 <= len(str(t)) <= 7]
        extra.extend(tickers)
        print(f"  GitHub ({csv_url.split('/')[-1]}): {len(tickers)}")
    except Exception as e:
        print(f"  ⚠️  GitHub failed: {e}")

# ETF universe (same as before)
ETFS = [
    "SPY","QQQ","DIA","IWM","IWB","MDY","IWR","IWS",
    "VTI","VB","VO","VV","ITOT","SCHB","SCHA","SCHM",
    "XLF","XLK","XLE","XLV","XLI","XLP","XLY","XLU","XLB","XLRE","XLC",
    "IYF","IYW","IYE","IYH","IYJ","IYC","IDU","IYM","IYR",
    "BND","AGG","TLT","IEF","SHY","LQD","HYG","JNK","MBB","TIP","BNDX",
    "VEA","VWO","EFA","EEM","IEFA","IEMG","VEU","ACWI","ACWX",
    "EWJ","EWG","EWU","EWC","EWA","EWZ","EWY","MCHI","INDA",
    "GLD","IAU","SLV","USO","UNG","DBC","PDBC","CORN","WEAT","SOYB",
    "VNQ","IYR","SCHH","REM","MORT",
    "VTV","VUG","IWD","IWF","MTUM","USMV","VLUE","QUAL","SIZE",
    "SPHB","SPHQ","SPLV","SPYD","NOBL","RDIV",
    "TQQQ","SQQQ","UPRO","SPXU","SSO","SDS","TNA","TZA",
    "VXX","UVXY","SVXY",
    "ARKK","ARKG","ARKW","ARKF","ARKQ",
    "ICLN","TAN","FAN","QCLN","PBW",
    "IBB","XBI","PJP",
    "SOXX","SMH","XSD",
    "JETS","XAR","ITA",
    "XRT","RETL",
]

ALL_TICKERS = sorted(set(sp500 + sp400 + sp600 + nasdaq100 + djia30 + extra + ETFS))
print(f"\n✅ Total unique tickers: {len(ALL_TICKERS)}")

# ============================================================
# CELL 5 — Download raw OHLCV (resumable, parallel)
# ============================================================
START_DATE  = "2000-01-01"
END_DATE    = "2024-12-31"
MAX_WORKERS = 5       # increase to 8 on a fast connection
SLEEP       = 0.1

COL_RENAMES = {
    "Open":"open","High":"high","Low":"low",
    "Close":"close","Adj Close":"adj_close",
    "Volume":"volume","Dividends":"dividends","Stock Splits":"stock_splits",
}

def download_ticker(ticker: str) -> dict:
    raw_file  = f"{RAW}/{ticker}.parquet"
    meta_file = f"{META}/{ticker}.json"
    if os.path.exists(raw_file) and os.path.exists(meta_file):
        return {"ticker": ticker, "status": "skipped"}
    try:
        t    = yf.Ticker(ticker)
        hist = t.history(start=START_DATE, end=END_DATE,
                         actions=True, auto_adjust=False)
        if isinstance(hist.columns, pd.MultiIndex):
            hist.columns = hist.columns.get_level_values(0)
        if hist.empty:
            return {"ticker": ticker, "status": "no_data"}
        hist.rename(columns=COL_RENAMES, inplace=True)
        hist.index = pd.to_datetime(hist.index).tz_localize(None)
        hist.to_parquet(raw_file)
        try:    info = t.info
        except: info = {}
        json.dump(info, open(meta_file,"w"), indent=2, default=str)
        return {"ticker": ticker, "status": "success"}
    except Exception as e:
        return {"ticker": ticker, "status": "error", "error": str(e)}

print(f"Downloading {len(ALL_TICKERS)} tickers  ({START_DATE} → {END_DATE})")
print("Already-downloaded files are skipped automatically.\n")

results = []
with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
    futures = {pool.submit(download_ticker, t): t for t in ALL_TICKERS}
    for f in tqdm(as_completed(futures), total=len(ALL_TICKERS), desc="Downloading"):
        results.append(f.result())
        time.sleep(SLEEP)

sc = pd.Series([r["status"] for r in results]).value_counts()
print("\n📊 Summary:", dict(sc))
errors = [r for r in results if r["status"]=="error"]
if errors:
    print("⚠️  First 10 errors:")
    for e in errors[:10]: print(f"   {e['ticker']}: {e.get('error','')}")

# ============================================================
# CELL 5 — Download (rate-limit safe, with retry + backoff)
# ============================================================
import logging
logging.getLogger("yfinance").setLevel(logging.CRITICAL)  # silence the delisted spam

START_DATE  = "2000-01-01"
END_DATE    = "2024-12-31"
MAX_WORKERS = 2       # reduced from 5 — Yahoo blocks aggressive parallel requests
MAX_RETRIES = 3       # retry each ticker up to 3 times before giving up

COL_RENAMES = {
    "Open":"open","High":"high","Low":"low",
    "Close":"close","Adj Close":"adj_close",
    "Volume":"volume","Dividends":"dividends","Stock Splits":"stock_splits",
}

def download_ticker(ticker: str) -> dict:
    raw_file  = f"{RAW}/{ticker}.parquet"
    meta_file = f"{META}/{ticker}.json"

    # Already downloaded — skip
    if os.path.exists(raw_file) and os.path.exists(meta_file):
        return {"ticker": ticker, "status": "skipped"}

    # Filter out obvious junk tickers before even trying
    # Warrants (W), Units (U), Rights (R) are usually not useful
    if len(ticker) > 5 and ticker[-1] in ("W", "U", "R"):
        return {"ticker": ticker, "status": "skipped_junk"}

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            t    = yf.Ticker(ticker)
            hist = t.history(
                start=START_DATE, end=END_DATE,
                actions=True, auto_adjust=False
            )
            if isinstance(hist.columns, pd.MultiIndex):
                hist.columns = hist.columns.get_level_values(0)
            if hist.empty:
                return {"ticker": ticker, "status": "no_data"}

            hist.rename(columns=COL_RENAMES, inplace=True)
            hist.index = pd.to_datetime(hist.index).tz_localize(None)
            hist.to_parquet(raw_file)

            try:    info = t.info
            except: info = {}
            json.dump(info, open(meta_file,"w"), indent=2, default=str)

            return {"ticker": ticker, "status": "success"}

        except Exception as e:
            err = str(e)

            # Rate limited — wait longer and retry
            if "Too Many Requests" in err or "Rate limit" in err or "429" in err:
                wait = 30 * attempt   # 30s, 60s, 90s
                print(f"\n⏳ Rate limited on {ticker}. Waiting {wait}s (attempt {attempt}/{MAX_RETRIES})…")
                time.sleep(wait)
                continue

            # Invalid crumb (Yahoo auth issue) — short wait and retry
            elif "Invalid Crumb" in err or "401" in err:
                time.sleep(10)
                continue

            # Delisted / no data — not worth retrying
            elif "possibly delisted" in err or "Data doesn't exist" in err:
                return {"ticker": ticker, "status": "no_data"}

            # Any other error — give up
            else:
                return {"ticker": ticker, "status": "error", "error": err}

    return {"ticker": ticker, "status": "error", "error": f"Failed after {MAX_RETRIES} retries"}


# Filter to only tickers not yet downloaded (true resume)
pending = [
    t for t in ALL_TICKERS
    if not (os.path.exists(f"{RAW}/{t}.parquet") and os.path.exists(f"{META}/{t}.json"))
]
print(f"Already downloaded : {len(ALL_TICKERS) - len(pending)}")
print(f"Remaining to fetch : {len(pending)}")
print(f"Workers: {MAX_WORKERS} | Retries: {MAX_RETRIES} | Starting…\n")

results = []
with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
    futures = {pool.submit(download_ticker, t): t for t in pending}
    for f in tqdm(as_completed(futures), total=len(pending), desc="Downloading"):
        res = f.result()
        results.append(res)
        # Adaptive delay — slow down after any rate limit hit
        if res["status"] == "error" and "rate" in res.get("error","").lower():
            time.sleep(5)
        else:
            time.sleep(0.5)   # base delay between every request (was 0.1 — too fast)

sc = pd.Series([r["status"] for r in results]).value_counts()
print("\n📊 Summary:", dict(sc))
errors = [r for r in results if r["status"] == "error"]
if errors:
    print(f"⚠️  {len(errors)} errors. First 10:")
    for e in errors[:10]:
        print(f"   {e['ticker']}: {e.get('error','')}")

# ============================================================
# CELL 6 — Combine into long-format OHLCV panel
# ============================================================
print("Building OHLCV panel…")
frames = []
for ticker in tqdm(ALL_TICKERS, desc="Loading"):
    fp = f"{RAW}/{ticker}.parquet"
    if not os.path.exists(fp): continue
    df = pd.read_parquet(fp)
    if df.empty: continue
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    df.rename(columns=COL_RENAMES, inplace=True)
    if "adj_close" not in df.columns and "close" in df.columns:
        df["adj_close"] = df["close"]
    df["ticker"] = ticker
    df.reset_index(inplace=True)
    df.rename(columns={"Date":"date","Datetime":"date","index":"date"},
              errors="ignore", inplace=True)
    frames.append(df)

panel = pd.concat(frames, ignore_index=True)
panel["date"] = pd.to_datetime(panel["date"]).dt.tz_localize(None)
panel.sort_values(["ticker","date"], inplace=True)
panel.reset_index(drop=True, inplace=True)
for c in ["dividends","stock_splits"]:
    if c in panel.columns: panel[c] = panel[c].fillna(0)

panel.to_parquet(f"{PROCESSED}/ohlcv_panel.parquet", index=False)
print(f"✅ ohlcv_panel.parquet — {panel.shape}")
print(f"   Tickers: {panel['ticker'].nunique()} | "
      f"Dates: {panel['date'].min().date()} → {panel['date'].max().date()}")

# Re-run this before Cell 7
import pandas as pd, numpy as np
from tqdm import tqdm

panel = pd.read_parquet("/content/drive/MyDrive/market_data/processed/ohlcv.parquet")
print(f"Panel loaded: {panel.shape}")

# Run this BEFORE Cell 7
import subprocess, sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "fastparquet", "-q"])
import os
print("✅ Ready")

# CELL 7 — Feature Engineering (memory-safe, ticker-by-ticker)
import gc
print("Engineering features (memory-safe mode)…")

def rsi(ret, n=14):
    g = ret.clip(lower=0)
    l = (-ret).clip(lower=0)
    ag = g.ewm(alpha=1/n, min_periods=n, adjust=False).mean()
    al = l.ewm(alpha=1/n, min_periods=n, adjust=False).mean()
    return 100 - 100/(1 + ag/al.replace(0,np.nan))

FEATURES_OUT = "/content/drive/MyDrive/market_data/processed/features.parquet"
COLS = ["date","ticker","return","log_return",
        "vol_5d","vol_21d","vol_63d","vol_252d",
        "mom_5d","mom_21d","mom_63d","mom_126d","mom_252d",
        "drawdown","max_dd_63d","max_dd_252d",
        "atr","atr_pct","rsi","macd","macd_signal","macd_hist",
        "bb_upper","bb_lower","bb_pct","bb_width",
        "dollar_volume","volume_zscore","volume_ratio",
        "high_52w","low_52w","pct_from_52w_high","pct_from_52w_low"]

all_tickers = panel["ticker"].unique()
CHUNK_SIZE  = 200   # process 200 tickers at a time, then write to disk

print(f"Total tickers: {len(all_tickers)}")
print(f"Processing in chunks of {CHUNK_SIZE}…\n")

# Delete output file if starting fresh
if os.path.exists(FEATURES_OUT):
    os.remove(FEATURES_OUT)
    print("Removed old features file.")

total_rows = 0
chunks = [all_tickers[i:i+CHUNK_SIZE] for i in range(0, len(all_tickers), CHUNK_SIZE)]

for chunk_idx, ticker_chunk in enumerate(tqdm(chunks, desc="Chunks")):

    feat_list = []

    # Only load rows for this chunk of tickers
    chunk_panel = panel[panel["ticker"].isin(ticker_chunk)].copy()

    for ticker, g in chunk_panel.groupby("ticker"):
        g = g.sort_values("date").copy()

        g["return"]     = g["adj_close"].pct_change()
        g["log_return"] = np.log(g["adj_close"]/g["adj_close"].shift(1))

        for w in [5,21,63,252]:
            g[f"vol_{w}d"] = g["return"].rolling(w).std() * np.sqrt(252)
            g[f"mom_{w}d"] = g["adj_close"].pct_change(w)
        g["mom_126d"] = g["adj_close"].pct_change(126)

        g["cummax"]      = g["adj_close"].cummax()
        g["drawdown"]    = (g["adj_close"] - g["cummax"]) / g["cummax"]
        g["max_dd_63d"]  = g["drawdown"].rolling(63).min()
        g["max_dd_252d"] = g["drawdown"].rolling(252).min()

        pc = g["close"].shift(1)
        tr = pd.concat([g["high"]-g["low"],
                        (g["high"]-pc).abs(),
                        (g["low"]-pc).abs()], axis=1).max(axis=1)
        g["atr"]     = tr.rolling(14).mean()
        g["atr_pct"] = g["atr"] / g["adj_close"]

        g["rsi"] = rsi(g["return"])

        e12 = g["adj_close"].ewm(span=12,adjust=False).mean()
        e26 = g["adj_close"].ewm(span=26,adjust=False).mean()
        g["macd"]        = e12-e26
        g["macd_signal"] = g["macd"].ewm(span=9,adjust=False).mean()
        g["macd_hist"]   = g["macd"] - g["macd_signal"]

        bm = g["adj_close"].rolling(20).mean()
        bs = g["adj_close"].rolling(20).std()
        g["bb_upper"] = bm+2*bs
        g["bb_lower"] = bm-2*bs
        g["bb_pct"]   = (g["adj_close"]-g["bb_lower"])/((g["bb_upper"]-g["bb_lower"]).replace(0,np.nan))
        g["bb_width"] = (g["bb_upper"]-g["bb_lower"])/bm

        g["dollar_volume"] = g["adj_close"]*g["volume"]
        vm = g["volume"].rolling(21).mean()
        vs = g["volume"].rolling(21).std().replace(0,np.nan)
        g["volume_zscore"] = (g["volume"]-vm)/vs
        g["volume_ratio"]  = g["volume"]/vm

        g["high_52w"]          = g["adj_close"].rolling(252).max()
        g["low_52w"]           = g["adj_close"].rolling(252).min()
        g["pct_from_52w_high"] = (g["adj_close"]-g["high_52w"])/g["high_52w"]
        g["pct_from_52w_low"]  = (g["adj_close"]-g["low_52w"]) /g["low_52w"]

        feat_list.append(g[[c for c in COLS if c in g.columns]])

    # Combine this chunk and append to parquet file on Drive
    chunk_df = pd.concat(feat_list, ignore_index=True)
    total_rows += len(chunk_df)

    if chunk_idx == 0:
        # First chunk — write fresh
        chunk_df.to_parquet(FEATURES_OUT, index=False)
    else:
        # Subsequent chunks — append by reading + writing
        # (pure parquet append isn't supported, so we use fastparquet)
        try:
            import fastparquet
            fastparquet.write(FEATURES_OUT, chunk_df, append=True)
        except ImportError:
            # fallback: accumulate in a temp folder instead
            chunk_df.to_parquet(
                f"/content/drive/MyDrive/market_data/processed/feat_chunk_{chunk_idx:04d}.parquet",
                index=False
            )

    # Free RAM
    del chunk_df, feat_list, chunk_panel
    gc.collect()

    if chunk_idx % 5 == 0:
        print(f"  Chunk {chunk_idx+1}/{len(chunks)} done — {total_rows:,} rows so far")

print(f"\n✅ Feature engineering complete — {total_rows:,} total rows")

"""##extra"""

# ============================================================
# CELL 7 — Feature engineering (no lookahead)
# ============================================================
print("Engineering features…")

def rsi(ret, n=14):
    g = ret.clip(lower=0)
    l = (-ret).clip(lower=0)
    ag = g.ewm(alpha=1/n, min_periods=n, adjust=False).mean()
    al = l.ewm(alpha=1/n, min_periods=n, adjust=False).mean()
    return 100 - 100/(1 + ag/al.replace(0,np.nan))

feat_list = []
for ticker, g in tqdm(panel.groupby("ticker"), desc="Features"):
    g = g.sort_values("date").copy()
    g["return"]     = g["adj_close"].pct_change()
    g["log_return"] = np.log(g["adj_close"]/g["adj_close"].shift(1))

    for w in [5,21,63,252]:
        g[f"vol_{w}d"] = g["return"].rolling(w).std() * np.sqrt(252)
        g[f"mom_{w}d"] = g["adj_close"].pct_change(w)

    g["mom_126d"] = g["adj_close"].pct_change(126)

    g["cummax"]      = g["adj_close"].cummax()
    g["drawdown"]    = (g["adj_close"] - g["cummax"]) / g["cummax"]
    g["max_dd_63d"]  = g["drawdown"].rolling(63).min()
    g["max_dd_252d"] = g["drawdown"].rolling(252).min()

    pc = g["close"].shift(1)
    tr = pd.concat([g["high"]-g["low"],
                    (g["high"]-pc).abs(),
                    (g["low"] -pc).abs()], axis=1).max(axis=1)
    g["atr"]     = tr.rolling(14).mean()
    g["atr_pct"] = g["atr"] / g["adj_close"]

    g["rsi"] = rsi(g["return"])

    e12=g["adj_close"].ewm(span=12,adjust=False).mean()
    e26=g["adj_close"].ewm(span=26,adjust=False).mean()
    g["macd"]        = e12-e26
    g["macd_signal"] = g["macd"].ewm(span=9,adjust=False).mean()
    g["macd_hist"]   = g["macd"] - g["macd_signal"]

    bm  = g["adj_close"].rolling(20).mean()
    bs  = g["adj_close"].rolling(20).std()
    g["bb_upper"] = bm+2*bs
    g["bb_lower"] = bm-2*bs
    g["bb_pct"]   = (g["adj_close"]-g["bb_lower"])/((g["bb_upper"]-g["bb_lower"]).replace(0,np.nan))
    g["bb_width"] = (g["bb_upper"]-g["bb_lower"])/bm

    g["dollar_volume"]  = g["adj_close"]*g["volume"]
    vm = g["volume"].rolling(21).mean()
    vs = g["volume"].rolling(21).std().replace(0,np.nan)
    g["volume_zscore"]  = (g["volume"]-vm)/vs
    g["volume_ratio"]   = g["volume"]/vm

    g["high_52w"]           = g["adj_close"].rolling(252).max()
    g["low_52w"]            = g["adj_close"].rolling(252).min()
    g["pct_from_52w_high"]  = (g["adj_close"]-g["high_52w"])/g["high_52w"]
    g["pct_from_52w_low"]   = (g["adj_close"]-g["low_52w"]) /g["low_52w"]

    COLS = ["date","ticker","return","log_return",
            "vol_5d","vol_21d","vol_63d","vol_252d",
            "mom_5d","mom_21d","mom_63d","mom_126d","mom_252d",
            "drawdown","max_dd_63d","max_dd_252d",
            "atr","atr_pct","rsi","macd","macd_signal","macd_hist",
            "bb_upper","bb_lower","bb_pct","bb_width",
            "dollar_volume","volume_zscore","volume_ratio",
            "high_52w","low_52w","pct_from_52w_high","pct_from_52w_low"]
    feat_list.append(g[[c for c in COLS if c in g.columns]])

features = pd.concat(feat_list, ignore_index=True)
features.to_parquet(f"{PROCESSED}/features.parquet", index=False)

# CELL 8 — find correct path + build returns matrix
import pandas as pd
import os
import gc

# Find correct path
possible_paths = [
    "/content/drive/MyDrive/market_data/processed/features.parquet",
    "/content/drive/MyDrive/fin_glassbox_market_data/processed/features.parquet",
]

FEATURES_PATH = None
for p in possible_paths:
    if os.path.exists(p):
        print(f"✅ Found: {p}")
        FEATURES_PATH = p
        break
    else:
        print(f"❌ Not found: {p}")

if FEATURES_PATH is None:
    # Search Drive to find it
    print("\nSearching Drive for features.parquet...")
    for root, dirs, files in os.walk("/content/drive/MyDrive"):
        for f in files:
            if f == "features.parquet":
                FEATURES_PATH = os.path.join(root, f)
                print(f"✅ Found at: {FEATURES_PATH}")
                break

if FEATURES_PATH is None:
    raise FileNotFoundError("features.parquet not found anywhere on Drive. Cell 7 may not have completed.")

# Set base processed folder from found path
PROCESSED = os.path.dirname(FEATURES_PATH)
print(f"Using processed folder: {PROCESSED}")

# Load only 3 columns to save RAM
print("\nBuilding returns matrix…")
returns_long = pd.read_parquet(FEATURES_PATH, columns=["date","ticker","return"])
print(f"✅ Loaded slim features: {returns_long.shape}")

returns_wide = (
    returns_long
    .pivot(index="date", columns="ticker", values="return")
)
returns_wide.sort_index(inplace=True)
returns_wide.to_parquet(f"{PROCESSED}/returns_panel.parquet")
print(f"✅ returns_panel.parquet — {returns_wide.shape}")

del returns_long
gc.collect()

if "SPY" in returns_wide.columns:
    rel = returns_wide.subtract(returns_wide["SPY"], axis=0)
    rel.to_parquet(f"{PROCESSED}/benchmark_relative.parquet")
    print(f"✅ benchmark_relative.parquet — {rel.shape}")
else:
    print("⚠️  SPY not found — skipping benchmark_relative.parquet")

del returns_wide
gc.collect()
print("\n✅ Cell 8 complete")

import pandas as pd
import os

paths = [
    "/content/drive/MyDrive/market_data/processed/features.parquet",
    "/content/drive/MyDrive/fin_glassbox_market_data/processed/features.parquet",
]

for p in paths:
    if os.path.exists(p):
        df = pd.read_parquet(p, columns=["ticker"])  # only load 1 column to save RAM
        print(f"✅ {p}")
        print(f"   Rows: {len(df):,}")
        del df
    else:
        print(f"❌ Not found: {p}")

##convert into CSV

import pandas as pd
import os

PROCESSED = "/content/drive/MyDrive/market_data/processed"
CSV_DIR   = f"{PROCESSED}/csv"
os.makedirs(CSV_DIR, exist_ok=True)

files = {
    "ohlcv_panel.parquet"          : "ohlcv_panel.csv",
    "features.parquet"             : "features.csv",
    "returns_panel.parquet"        : "returns_panel.csv",
    "benchmark_relative.parquet"   : "benchmark_relative.csv",
}

for parquet_name, csv_name in files.items():
    parquet_path = f"{PROCESSED}/{parquet_name}"
    csv_path     = f"{CSV_DIR}/{csv_name}"

    if not os.path.exists(parquet_path):
        print(f"❌ Not found: {parquet_name} — skipping")
        continue

    print(f"Converting {parquet_name}…")
    df = pd.read_parquet(parquet_path)
    df.to_csv(csv_path, index=False)

    size_mb = os.path.getsize(csv_path) / 1024**2
    print(f"✅ {csv_name} — {len(df):,} rows — {size_mb:.1f} MB")
    del df

print("\n✅ All CSVs saved to:", CSV_DIR)

import os
folder = "/content/drive/MyDrive/market_data/raw"
num_files = len([f for f in os.listdir(folder) if os.path.isfile(os.path.join(folder, f))])
print(num_files)